language: node_js
node_js:
#  - "0.10"
  - "4.9"
  #- "6.9"
  #- "8.2"
  #- "10.12"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev
  - sudo apt-get install -y zip unzip
  - wget https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip
  - unzip terraform_0.12.7_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - terraform --version

script:
  - chmod +x script.sh
  - export AWS_ACCESS_KEY_ID=$access_key_id
  - export AWS_SECRET_ACCESS_KEY="$secret_access_key"
  - terraform init
  - terraform plan
  - terraform destroy -auto-approve
  - terraform apply -auto-approve
  - npm install
  - npm run build
  - zip -r eb.zip *  
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id:
    secure: "$access_key_id"
  secret_access_key:
    secure: "$secret_access_key"
  region: "eu-central-1"
  app: "mychess"
  env: "Mychess-env1"
  bucket_name: "lv428chess"
  zip_file: eb.zip
on:
    branch: master
env:
  - DB=mongodb



 
