language: node_js
node_js:
  - "0.10"
  - "4.9"
  - "6.9"
  - "8.2"
  - "10.12"
before_install:
  - sudo apt-get install -y zip
script:
   #			  npm build
#			  sudo npm run build
 #             npm start & sudo npm run client
  - npm install
  - npm run build
  - zip -r eb.zip *  
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id:
    secure: "$access_key_id"
  secret_access_key:
    secure: "$secret_access_key"
  region: "eu-central-1"
  app: "mychess"
  env: "Mychess-env1"
  bucket_name: "lv428chess"
  zip_file: eb.zip
on:
    branch: master
env:
- DB=mongodb




 
